routes/user.py
import extensions
import uuid
import sys

from models.user import User
from models.token import AuthToken

from flask import request, g, Blueprint, send_from_directory
from routes.route_utilities import table_get
from routes.dbfile import download

auth = extensions.auth
db = extensions.db
dataResultSuccess = extensions.dataResultSuccess
resultSuccess = extensions.resultSuccess
resultFailure = extensions.resultFailure

user_blueprint = Blueprint("user", __name__, url_prefix="/user")


@user_blueprint.route('', methods=['GET', 'POST', 'PATCH', 'DELETE'])
def endpoint_user():
    if (request.method == 'POST'):
        return new_user()
    elif (request.method == 'GET'):
        return query_user()
    elif (request.method == 'PATCH'):
        return update_user()
    else:
        return delete_user_path()


# TODO make sure this returns user details if not admin, or add <me> path that returns the user
@auth.login_required(2)
def query_user():
    return table_get(User)


def new_user(data=None, norequest=False):  # TODO require admin status to be able to make this
    requestJson = data or request.get_json(force=True)
    username = requestJson['username']
    password = requestJson['password']
    if username is None or password is None:
        if (norequest):
            return None
        else:
            return resultFailure(msg='Missing Data', code=400)    # missing arguments
    if User.query.filter_by(username=username).first() is not None:
        if (norequest):
            return None
        else:
            return resultFailure(msg='Existing User', code=400)    # existing user
    user = User(**requestJson)
    user.hash_password(password)
    user.guid = user.guid or uuid.uuid4()
    db.session.add(user)
    db.session.commit()
    if (norequest):
        return user
    else:
        return dataResultSuccess(user.to_dict(), code=201, spuriousParameters=list(request.args.to_dict().keys()))


@auth.login_required(1)
def update_user():  # TODO require an admin or the user himself to do this
    args = request.args.to_dict()
    body = request.get_json(force=True)
    user = None
    if (g.authLevel > 1):
        if ('guid' in args):
            guid = args.pop('guid')
            user = User.query.filter_by(guid=guid).first()
        elif ('id' in args):
            uid = args.pop('id')
            user = User.query.filter_by(id=uid).first()
        else:
            user = g.user
        if (user is None):
            resultFailure("No user found.", 404)
    else:
        user = g.user
    new_user = edit_user(user, **body)
    return dataResultSuccess(new_user.to_dict(), code=200, spuriousParameters=list(args.keys()))


def edit_user(user, **changes):
    user.set_columns(**changes)
    if ('password' in changes):
        user.hash_password(changes['password'])
        userToken = AuthToken.query.filter_by(user=user).first()
        userToken.revoked = True
    return user


@auth.login_required(1)
def delete_user_path():
    return delete_user()


#TODO deleting the user himself if he/she gets the id wrong or is not an admin is a tad bit too extreme
def delete_user(**data):
    args = request.args.to_dict() or data
    user = None
    if (g.authLevel > 1):
        if ('guid' in args):
            guid = args.pop('guid')
            user = User.query.filter_by(guid=guid).first()
        elif ('id' in args):
            uid = args.pop('id')
            user = User.query.filter_by(id=uid).first()
        else:
            user = g.user
        if (user is None):
            resultFailure("No user found.", 404)
    else:
        user = g.user
    token = AuthToken.query.filter_by(userid=user.id).first()
    db.session.delete(user)
    if (token is not None):
        db.session.delete(token)
    #TODO also delete any dbfiles related to the user
    db.session.commit()
    if (data['norequest']):
        return True
    return extensions.resultSuccess(msg="Item deleted", code=200, spuriousParameters=list(args.keys()))


@user_blueprint.route('/info')
@auth.login_required(1)
def get_user_info():
    return dataResultSuccess({
        'authlevel': g.authLevel,
        'code': g.user.code or g.user.username,
        'email': g.user.email,
        'guid': g.user.guid,
        'userid': g.user.id,
    }, spuriousParameters=list(request.args.to_dict().keys()))


@user_blueprint.route('/avatar/<int:id>')
def get_user_profile_picture(id=None):
    user = User.query.filter_by(id=id).first()
    if (user is not None):
        print(sys.path[0] + 'static/assets/images/avatar.png')
        return (download(norequest=True, code='PHOTO', masterid=user.guid) or send_from_directory(sys.path[0] + 'static/assets/images', 'avatar.png'))

templates/lumberjack/datatable.html.j2
{%extends 'lumberjack/layout.html.j2'%}
{%block head%}
<!--<link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />-->
<!-- Start datatable css -->
<link rel="stylesheet" type="text/css" href="/static/assets/css/dataTables/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="/static/assets/css/dataTables/dataTables.bootstrap4.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.jqueryui.min.css">
{%endblock%}
{%block content%}
<div class="row">
    <div class="col-12 mt-5">
        <div class="card">
            <div class="card-body">

                <div class="row justify-content-between" style="margin-right: 0px">
                <h4 class="header-title">{{name}}</h4><a class="btn btn-primary" href="{{request.path + '/new'}}">Add Item</a>
                </div>
                <div class="data-tables datatable-primary">
                    <table id="dataTable" class="text-center">
                        <thead class="text-capitalize">
                            <tr>
                                {%for item in headList%}
                                <th>{{item}}</th>
                                {%endfor%}
                            </tr>
                        </thead>
                        <tbody>
                            {%for item in dataList%}
                            <tr>
                                {%for value in headList%}
                                <td>{{item[value]}}</td>
                                {%endfor%}
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}
{%block scripts%}
<!-- Start datatable js -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap.min.js"></script>
{%endblock%}

</html>

templates/lumberjack/edit-item.html.j2
{% extends 'lumberjack/layout.html.j2'%}
{% import "bootstrap/wtf.html" as wtf %}

{%block content%}{{wtf.quick_form(form=content, button_map={'submit':'primary'})}}{%endblock%}

templates/lumberjack/layout.html.j2
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{name}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="/static/assets/images/icon/lumberjack.ico">
    <link rel="stylesheet" href="/static/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/assets/css/themify-icons.css">
    <link rel="stylesheet" href="/static/assets/css/metisMenu.css">
    <link rel="stylesheet" href="/static/assets/css/slicknav.min.css">
    {%block head%}{%endblock%}
    <!-- others css -->
    <link rel="stylesheet" href="/static/assets/css/typography.css">
    <link rel="stylesheet" href="/static/assets/css/default-css.css">
    <link rel="stylesheet" href="/static/assets/css/styles.css">
    <link rel="stylesheet" href="/static/assets/css/responsive.css">
    <!-- modernizr css -->
    <script src="/static/assets/js/vendor/modernizr-2.8.3.min.js"></script>
    
</head>

<body>
    
    <!-- preloader area start -->
    <div id="preloader">
        <div class="loader"></div>
    </div>
    <!-- preloader area end -->
    <!-- page container area start -->
    <div class="page-container">
        <!-- sidebar menu area start -->
        <div class="sidebar-menu">
            <div class="sidebar-header">
                <div class="logo">
                    <img src="/static/assets/images/icon/logo.svg" alt="logo">
                </div>
            </div>
            <div class="main-menu">
                <div class="menu-inner"> 
                    <nav>
                        <ul class="metismenu" id="menu">
                            {% for item in sidebarItems %}
                            {% if request.path == item.ref %}
                            <li class="active">
                            {% else %}
                            <li>
                            {% endif %}
                                <a href="{{item.ref}}" aria-expanded="true"><i class="{{item.icon}}""></i><span>{{item.name}}</span></a>
                                {% if item.ref == "javascript:void(0)" %}
                                    <ul class="collapse">
                                        {% for subitem in item.children %}
                                        <li>
                                            <a href="{{subitem.ref}}" aria-expanded="true">{{subitem.name}}</a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </li>
                            {% endfor %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <!-- sidebar menu area end -->
        <!-- main content area start -->
        <div class="main-content">
            <!-- page title area start -->
            <div class="page-title-area">
                <div class="nav-btn pull-left">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                <div class="row align-items-center">
                    <div class="col-sm-6">
                        <div class="breadcrumbs-area clearfix">
                            <h4 class="page-title pull-left">{{name}}</h4>
                        </div>
                    </div>
                    
                    <div class="col-sm-6 clearfix">
                        <div class="row align-items-center justify-content-end">
                            <ul class="notification-area pull-right">
                                <li id="full-view"><i class="ti-fullscreen"></i></li>
                                <li id="full-view-exit"><i class="ti-zoom-out"></i></li>
                            </ul>
                            <div class="user-profile pull-right dropdown-toggle" data-toggle="dropdown" style="cursor: pointer;">

                                <img class="avatar user-thumb" src={{url_for('user.get_user_profile_picture', id=g.user.id, _external=True)}} alt="avatar">
                                <h4 class="user-name dropdown-toggle" >{{g.user.username}}</h4>

                            </div>
                            <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(45px, 45px, 0px); top: 0px; left: 0px; will-change: transform;">
                                <a class="dropdown-item" href="{{url_for('panel.panel_logout')}}"><i class="fa fa-sign-out"></i>  Log Out</a>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
            <!-- page title area end -->
            <div class="main-content-inner">
                {%block content%}{%endblock%}
            </div>
        <!-- main content area end -->
        <!-- footer area start-->
        <footer>
            <div class="footer-area">
                <p>© Copyright 2020 <a href="https://reampt.com">Reampt</a>.  All right reserved. </p>
            </div>
        </footer>
        <!-- footer area end-->
    </div>
    <!-- page container area end -->
   
    <!-- jquery latest version -->
    <script src="/static/assets/js/vendor/jquery-2.2.4.min.js"></script>
    <!-- bootstrap 4 js -->
    <script src="/static/assets/js/popper.min.js"></script>
    <script src="/static/assets/js/bootstrap.min.js"></script>
    <script src="/static/assets/js/owl.carousel.min.js"></script>
    <script src="/static/assets/js/metisMenu.min.js"></script>
    <script src="/static/assets/js/jquery.slimscroll.min.js"></script>
    <script src="/static/assets/js/jquery.slicknav.min.js"></script>

    {%block scripts%}{%endblock%}

    <script src="/static/assets/js/plugins.js"></script>
    <script src="/static/assets/js/scripts.js"></script>
</body>

</html>

templates/lumberjack/login.html
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="/static/assets/images/icon/lumberjack.ico">
    <link rel="stylesheet" href="/static/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/assets/css/themify-icons.css">
    <link rel="stylesheet" href="/static/assets/css/metisMenu.css">
    <link rel="stylesheet" href="/static/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/assets/css/slicknav.min.css">
    <!-- others css -->
    <link rel="stylesheet" href="/static/assets/css/typography.css">
    <link rel="stylesheet" href="/static/assets/css/default-css.css">
    <link rel="stylesheet" href="/static/assets/css/styles.css">
    <link rel="stylesheet" href="/static/assets/css/responsive.css">
    <!-- modernizr css -->
    <script src="/static/assets/js/vendor/modernizr-2.8.3.min.js"></script>
</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- preloader area start -->
    <div id="preloader">
        <div class="loader"></div>
    </div>
    <!-- preloader area end -->
    <!-- login area start -->
    <div class="login-area">
        <div class="container">
            <div class="login-box ptb--100">
                <form method="POST">
                    <div class="login-form-head">
                        <h4>Sign In</h4>
                        <p>Hello there, Sign in and start using your Panel</p>
                    </div>
                    <div class="login-form-body">
                        <div class="form-gp">
                            <label for="username">User Name</label>
                            <input type="text" name="username" id="username">
                            <i class="ti-user"></i>
                            <div class="text-danger"></div>
                        </div>
                        <div class="form-gp">
                            <label for="password">Password</label>
                            <input type="password" name="password" id="password">
                            <i class="ti-lock"></i>
                            <div class="text-danger"></div>
                        </div>
                        <div class="row mb-4 rmber-area invisible">
                            <div class="col-6">
                                <div class="custom-control custom-checkbox mr-sm-2">
                                    <input type="checkbox" class="custom-control-input" id="customControlAutosizing">
                                    <label class="custom-control-label" for="customControlAutosizing">Remember Me</label>
                                </div>
                            </div>
                            <div class="col-6 text-right">
                                <a href="#">Forgot Password?</a>
                            </div>
                        </div>
                        <div class="submit-btn-area">
                            <button id="form_submit" type="submit">Submit <i class="ti-arrow-right"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- login area end -->

    <!-- jquery latest version -->
    <script src="/static/assets/js/vendor/jquery-2.2.4.min.js"></script>
    <!-- bootstrap 4 js -->
    <script src="/static/assets/js/popper.min.js"></script>
    <script src="/static/assets/js/bootstrap.min.js"></script>
    <script src="/static/assets/js/owl.carousel.min.js"></script>
    <script src="/static/assets/js/metisMenu.min.js"></script>
    <script src="/static/assets/js/jquery.slimscroll.min.js"></script>
    <script src="/static/assets/js/jquery.slicknav.min.js"></script>
    
    <!-- others plugins -->
    <script src="/static/assets/js/plugins.js"></script>
    <script src="/static/assets/js/scripts.js"></script>
</body>

</html>